from pathlib import Path

import joblib

model_path = Path("models/trained/gesture_model_int8.tflite")
output_path = Path("firmware/src/model_data.cpp")
config_output_path = Path("firmware/include/model_config.h")

scaler = joblib.load("models/trained/scaler.pkl")
label_encoder = joblib.load("models/trained/label_encoder.pkl")

# Must match the sampling rate / window length used to record
# data/public/gesture_dataset/gesture_dataset.csv (50 samples per gesture,
# ~20ms apart -> 50 Hz).
SAMPLE_INTERVAL_MS = 20
WINDOW_SIZE = 50

SENSOR_COLUMNS = ["ax", "ay", "az", "gx", "gy", "gz"]

data = model_path.read_bytes()

with open(output_path, "w") as f:
    f.write('#include "model_data.h"\n\n')
    f.write("const unsigned char model_data[] = {\n")

    for i, b in enumerate(data):
        if i % 12 == 0:
            f.write("    ")
        f.write(f"0x{b:02x}, ")
        if i % 12 == 11:
            f.write("\n")

    f.write("\n};\n\n")
    f.write(f"const unsigned int model_data_len = {len(data)};\n")

print("Model converted successfully!")
print(f"Model size: {len(data)} bytes")

with open(config_output_path, "w") as f:
    f.write("#ifndef MODEL_CONFIG_H\n")
    f.write("#define MODEL_CONFIG_H\n\n")
    f.write("// Auto-generated by convert_model.py from models/trained/scaler.pkl\n")
    f.write("// and models/trained/label_encoder.pkl. Do not edit by hand -\n")
    f.write("// re-run convert_model.py after retraining instead.\n\n")

    f.write(f"#define NUM_CHANNELS {len(SENSOR_COLUMNS)}\n")
    f.write("#define NUM_FEATURES_PER_CHANNEL 5\n")
    f.write("#define NUM_FEATURES (NUM_CHANNELS * NUM_FEATURES_PER_CHANNEL)\n")
    f.write(f"#define WINDOW_SIZE {WINDOW_SIZE}\n")
    f.write(f"#define SAMPLE_INTERVAL_MS {SAMPLE_INTERVAL_MS}\n")
    f.write(f"#define NUM_CLASSES {len(label_encoder.classes_)}\n\n")

    f.write("// Order must match sensor_columns in src/feature_extraction.py: ax, ay, az, gx, gy, gz\n")
    mean_values = ", ".join(f"{v:.8f}f" for v in scaler.mean_)
    scale_values = ", ".join(f"{v:.8f}f" for v in scaler.scale_)
    f.write(f"static const float SCALER_MEAN[NUM_CHANNELS] = {{{mean_values}}};\n")
    f.write(f"static const float SCALER_SCALE[NUM_CHANNELS] = {{{scale_values}}};\n\n")

    f.write("// Index order matches sklearn LabelEncoder's sorted class order (alphabetical).\n")
    class_values = ", ".join(f'"{c}"' for c in label_encoder.classes_)
    f.write(f"static const char* const CLASS_NAMES[NUM_CLASSES] = {{{class_values}}};\n\n")

    f.write("#endif\n")

print("Firmware model_config.h generated successfully!")
print(f"Classes: {list(label_encoder.classes_)}")
