#ifndef MODEL_CONFIG_H
#define MODEL_CONFIG_H

// Auto-generated by convert_model.py from models/trained/scaler.pkl
// and models/trained/label_encoder.pkl. Do not edit by hand -
// re-run convert_model.py after retraining instead.

#define NUM_CHANNELS 6
#define NUM_FEATURES_PER_CHANNEL 5
#define NUM_FEATURES (NUM_CHANNELS * NUM_FEATURES_PER_CHANNEL)
#define WINDOW_SIZE 50
#define SAMPLE_INTERVAL_MS 20
#define NUM_CLASSES 5

// Order must match sensor_columns in src/feature_extraction.py: ax, ay, az, gx, gy, gz
static const float SCALER_MEAN[NUM_CHANNELS] = {0.65737252f, -0.14758747f, 0.48926145f, -15.83589921f, -19.87894484f, 2.44556688f};
static const float SCALER_SCALE[NUM_CHANNELS] = {0.37330181f, 0.47802026f, 0.41957263f, 58.38757779f, 86.17395066f, 64.59898916f};

// Index order matches sklearn LabelEncoder's sorted class order (alphabetical).
static const char* const CLASS_NAMES[NUM_CLASSES] = {"flick_down", "flick_up", "idle", "wave_left", "wave_right"};

#endif
